openapi: 3.1.0
info:
  version: 1.0.0
  title: Travellers app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of travellers app
tags:
  - name: Auth
    description: Auth operations.

  - name: Users
    description: Operations about users.

  - name: Stories
    description: Operations about stories.

servers:
  - url: http://localhost:3001
  # - url: https://example.com/api/v1
paths:
  #
  # Auth
  /api/auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml

  /api/auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  /api/auth/request-reset-password:
    post:
      $ref: ../swagger/paths/auth/request-reset-password.yaml

  # Stories
  /api/stories:
    get:
      $ref: ../swagger/paths/stories/get-public-stories.yaml

    post:
      $ref: ../swagger/paths/stories/create-story.yaml
  # --
  /api/stories/{id}:
    get:
      $ref: ../swagger/paths/stories/get-story-by-id.yaml

    delete:
      $ref: ../swagger/paths/stories/delete-story.yaml
  # --
  /api/stories/update-story/{id}:
    patch:
      $ref: ../swagger/paths/stories/update-story.yaml

  /api/stories/categories:
    get:
      $ref: ../swagger/paths/stories/get-categories.yaml

  # Users
  /api/users:
    get:
      $ref: ../swagger/paths/users/get-all-users.yaml

  /api/users/profile/{id}:
    get:
      $ref: ../swagger/paths/users/get-private-profile.yaml

  /api/users/public/{id}:
    get:
      $ref: ../swagger/paths/users/get-public-profile.yaml

  /api/users/toggle-save-story/{id}:
    patch:
      $ref: ../swagger/paths/users/patch-saved-story.yaml

  /api/users/upload-avatar:
    post:
      $ref: ../swagger/paths/users/upload-avatar.yaml

  /api/users/delete-avatar:
    delete:
      $ref: ../swagger/paths/users/delete-avatar.yaml

  /api/users/update-info:
    post:
      $ref: ../swagger/paths/users/update-user-info.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
