openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3001
  # - url: https://example.com/api/v1
paths:
  /api/users:
    get:
      $ref: ../swagger/paths/users/get-all-users.yaml

  /api/users/profile/{id}:
    get:
      $ref: ../swagger/paths/users/get-private-profile.yaml

  /api/users/public/{id}:
    get:
      $ref: ../swagger/paths/users/get-public-profile.yaml

  /api/users/toggle-save-story/{id}:
    patch:
      $ref: ../swagger/paths/users/patch-saved-story.yaml

  /api/users/upload-avatar:
    post:
      $ref: ../swagger/paths/users/upload-avatar.yaml

  /api/users/delete-avatar:
    delete:
      $ref: ../swagger/paths/users/delete-avatar.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
